#!/usr/bin/env bash
# Build the public marketing home + docs into ./public-site for a static host.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/public-site"
HOME_DIR="$ROOT/sites/work4you-home"
DOCS_DIR="$ROOT/website"

rm -rf "$OUT"
mkdir -p "$OUT"

echo "==> Building home ($HOME_DIR)"
(
  cd "$HOME_DIR"
  if [[ -f package-lock.json ]]; then npm ci; else npm install; fi
  npm run build
)
cp -a "$HOME_DIR/dist/." "$OUT/"

echo "==> Publishing install scripts at site root"
cp "$ROOT/scripts/install.sh" "$OUT/install.sh"
cp "$ROOT/scripts/install.ps1" "$OUT/install.ps1"
chmod 644 "$OUT/install.sh" "$OUT/install.ps1"

echo "==> Building docs ($DOCS_DIR)"
# Skills Hub catalog (skills.json) is a gitignored build artifact. prebuild.mjs
# runs extract-skills.py; PyYAML is required to parse SKILL.md frontmatter.
if command -v python3 >/dev/null 2>&1; then
  python3 -m pip install --user -q 'pyyaml==6.0.2' || true
fi
# userStories.json is local data for the collage; ensure build can resolve it.
mkdir -p "$DOCS_DIR/src/data"
if [[ ! -f "$DOCS_DIR/src/data/userStories.json" ]]; then
  echo '[]' > "$DOCS_DIR/src/data/userStories.json"
fi
(
  cd "$DOCS_DIR"
  # website/engines asks for npm >= 11.17; use npm@12 via npx for hermetic CI hosts.
  if [[ -f package-lock.json ]]; then npx -y npm@12 ci; else npx -y npm@12 install; fi
  # English-only is enough for the public docs surface and is faster/more reliable in CI.
  npx -y npm@12 run build:fast
)
mkdir -p "$OUT/docs"
cp -a "$DOCS_DIR/build/." "$OUT/docs/"

# Optional agent indexes generated by website prebuild (if present at docs root of build).
if [[ -f "$DOCS_DIR/build/llms.txt" ]]; then
  cp -a "$DOCS_DIR/build/llms.txt" "$OUT/llms.txt"
fi
if [[ -f "$DOCS_DIR/build/llms-full.txt" ]]; then
  cp -a "$DOCS_DIR/build/llms-full.txt" "$OUT/llms-full.txt"
fi

echo "==> public-site ready: $OUT"
du -sh "$OUT"
